parsing_new_package_omer
fthrslntgy/tulpar-interface pull request #19
Opened 2023-02-05 21:44 UTC by omerilbilgi

2023-02-05 21:45 UTC, omerilbilgi commented
parsing_new_package_omer

2023-02-09 00:44 UTC, fthrslntgy requested changes

2023-02-09 00:44 UTC, fthrslntgy commented on communication.py
> +        paket_no = line[4] + line[5]
where is third byte? all of the numbers below here are written as one more than they should be. fix it.

2023-02-09 00:44 UTC, fthrslntgy commented on communication.py
> +    #    return_number = line[82]
remove all old lines. these are unusable for this year. delete all.

2023-02-09 00:44 UTC, fthrslntgy commented on communication.py
> +    #    row.append(latitude_car)
remove all old lines at here (row.append part)

2023-02-09 00:44 UTC, fthrslntgy commented on communication.py
>          # print(row)
you can uncomment printing row.

2023-02-09 00:44 UTC, fthrslntgy commented on communication.py
>          self.widget.graphs.update_sp_tmp_v(abs(speed), tempe, b_voltage)
all lines below here should be in comment. this part is unusable for now. you should check that is your parsing valid. visualize data later.

2023-02-09 00:44 UTC, fthrslntgy commented on constants.py
> +COMMAND = ("START", "STOP", "RECORD", "PAUSE", "UNPAUSE", "UNRECORD")
nice

2023-02-09 00:46 UTC, fthrslntgy commented on communication.py
> +        takim_no = takim_no * 8
this part is written for team number at last year. that number was more bigger than 2 bytes and after received that, we were multiplying it with 8. (so it was sended as divided by 8). this part is not necessary for now.

2023-04-02 23:20 UTC, fthrslntgy commented
merge conflict since oruc's changes. cant merged but not invalid.

2023-04-02 23:20 UTC, closed without merging